### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'qRegisterResourceData'

### ISSUE THREAD

**Issue by alina-gotovtseva** [shotgunsoftware/tk-toolchain#42]
Hi everyone!

I'd like to use tk-toolchain for running apps from the command line, and now trying to run the [official starter app](https://github.com/shotgunsoftware/tk-multi-starterapp) to see how it works.

I’ve installed latest tk-toolchain from master with pip and cloned the Toolkit-based repositories near my folder with app, as specified in [pre-requisites](https://github.com/shotgunsoftware/tk-toolchain#pre-requisites).

I’m running it with `python -m tk_toolchain.cmd_line_tools.tk_run_app` command, and get an error:

```
PS C:\Users\alinag\PycharmProjects\tk-multi-starterapp> python -m tk_toolchain.cmd_line_tools.tk_run_app
Python Version: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Launching test engine in context {'type': 'Project', 'id': 70}
[0.0] Resolving project...
[0.05] Resolving configuration...
[0.1] Updating configuration...
[0.15] Starting up Toolkit...
[0.2] Checking tk_testengine Undefined (1 of 5).
[0.33999999999999997] Checking tk-multi-starterapp Undefined (2 of 5).     
[0.48] Checking tk-framework-qtwidgets Undefined (3 of 5).                 
[0.6199999999999999] Checking tk-framework-shotgunutils Undefined (4 of 5).
[0.76] Checking tk-framework-widget Undefined (5 of 5).                    
[0.95] Resolving context...                                                
[0.97] Launching Engine...
[ERROR sgtk.env.test.tk-testengine] App C:\Users\alinag\PycharmProjects\tk-multi-starterapp failed to initialize. It will not be loaded.
Traceback (most recent call last):
  File "C:\Users\alinag\AppData\Roaming\Shotgun\test\p70\cfg\install\core\python\tank\platform\engine.py", line 2793, in __load_apps
    app.init_app()
  File "C:\Users\alinag\PycharmProjects\tk-multi-starterapp\app.py", line 30, in init_app
    app_payload = self.import_module("app")
  File "C:\Users\alinag\AppData\Roaming\Shotgun\test\p70\cfg\install\core\python\tank\platform\bundle.py", line 461, in import_module
    imp.load_module(
  File "C:\Program Files\Python39\lib\imp.py", line 244, in load_module
    return load_package(name, filename)
  File "C:\Program Files\Python39\lib\imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\alinag\PycharmProjects\tk-multi-starterapp\python\__init__.py", line 11, in <module>
    from . import app
  File "C:\Users\alinag\PycharmProjects\tk-multi-starterapp\python\app\__init__.py", line 11, in <module>
    from . import dialog
  File "C:\Users\alinag\PycharmProjects\tk-multi-starterapp\python\app\dialog.py", line 19, in <module>
    from .ui.dialog import Ui_Dialog
  File "C:\Users\alinag\PycharmProjects\tk-multi-starterapp\python\app\ui\dialog.py", line 39, in <module>
    from . import resources_rc
  File "C:\Users\alinag\PycharmProjects\tk-multi-starterapp\python\app\ui\resources_rc.py", line 20, in <module>
    qInitResources()
  File "C:\Users\alinag\PycharmProjects\tk-multi-starterapp\python\app\ui\resources_rc.py", line 15, in qInitResources
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\alinag\PycharmProjects\tk-multi-starterapp\python\__init__.py", line 11, in <module>
    from . import app
  File "C:\Users\alinag\PycharmProjects\tk-multi-starterapp\python\app\__init__.py", line 11, in <module>
    from . import dialog
  File "C:\Users\alinag\PycharmProjects\tk-multi-starterapp\python\app\dialog.py", line 19, in <module>
    from .ui.dialog import Ui_Dialog
  File "C:\Users\alinag\PycharmProjects\tk-multi-starterapp\python\app\ui\dialog.py", line 39, in <module>
    from . import resources_rc
  File "C:\Users\alinag\PycharmProjects\tk-multi-starterapp\python\app\ui\resources_rc.py", line 20, in <module>
    qInitResources()
  File "C:\Users\alinag\PycharmProjects\tk-multi-starterapp\python\app\ui\resources_rc.py", line 15, in qInitResources
    QtCore.qRegisterResourceData(0x01, qt_resource_struct, qt_resource_name, qt_resource_data)
AttributeError: 'NoneType' object has no attribute 'qRegisterResourceData'
[1] Engine launched.
[1] Engine launched.
Available application commands (long and short versions):
[]
The following commands will be run:
[]
No commands were found. It is possible the application failed to initialize?
```
Looks like Qt setup went wrong, does anyone know why this could happen?

I’ve tried to run the other apps, but I get the same AttributeError, with missing Qt classes attributes. Could there be something wrong with my setup/configuration?

**Comment by alina-gotovtseva** [comment]
The issue was resolved by running `pip install PySide2` 🥲
